# -*- coding: utf-8 -*-
"""Baseline_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IOKjoRjoxC86zi-yvBgvKR_jwTeBs-tI
"""

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader, random_split

from PIL import ImageFile

ImageFile.LOAD_TRUNCATED_IMAGES = True

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

from google.colab import drive
drive.mount('/content/drive')

!unzip -q "/content/drive/MyDrive/dataset/archive.zip" -d "/content/dataset"

print("Cat-Dog dataset extracted!")

!unzip -q "/content/drive/MyDrive/ood/ood.zip" -d "/content/ood_images"

print("OOD dataset extracted!")

import os

print(os.listdir("/content/ood_images/dataset")[:20])
print("Count:", len(os.listdir("/content/ood_images/dataset")))

import os

print(os.listdir("/content/dataset"))

train_transform = transforms.Compose([

    transforms.Resize((224, 224)),

    transforms.RandomHorizontalFlip(),

    transforms.RandomRotation(10),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


val_transform = transforms.Compose([

    transforms.Resize((224, 224)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

full_dataset = datasets.ImageFolder(
    root="/content/dataset/PetImages"
)

train_size = int(0.8 * len(full_dataset))
val_size = len(full_dataset) - train_size

train_dataset, val_dataset = random_split(
    full_dataset,
    [train_size, val_size]
)

train_dataset.dataset.transform = train_transform

val_dataset.dataset.transform = val_transform

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True,
    num_workers=2
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2
)

class GaussianLayer(nn.Module):

    def __init__(self, in_features, num_classes):
        super(GaussianLayer, self).__init__()

        self.num_classes = num_classes
        self.in_features = in_features


        # Learnable class centers
        self.mu = nn.Parameter(
            torch.randn(num_classes, in_features)
        )


        # Learnable spreads
        self.sigma = nn.Parameter(
            torch.ones(num_classes, in_features)
        )


    def forward(self, x):

        # x shape:
        # [batch_size, in_features]

        x = x.unsqueeze(1)

        mu = self.mu.unsqueeze(0)

        sigma = torch.abs(self.sigma.unsqueeze(0)) + 1e-6


        # Mahalanobis-like distance
        distances = ((x - mu) ** 2) / (2 * sigma ** 2)


        # Negative distance as logits
        logits = -distances.sum(dim=2)


        return logits, distances.sum(dim=2)

model = models.efficientnet_b0(pretrained=True)

num_features = model.classifier[1].in_features

model.classifier[1] = GaussianLayer(
    num_features,
    2
)

model = model.to(device)

for param in model.features.parameters():
    param.requires_grad = False

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.classifier.parameters(),
    lr=0.001
)

#scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    #optimizer,
    #mode='min',
    #factor=0.5,
    #patience=1
#)

scaler = torch.cuda.amp.GradScaler()

num_epochs = 10

for epoch in range(num_epochs):

    model.train()

    running_loss = 0.0

    correct = 0
    total = 0


    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)


        optimizer.zero_grad()


        outputs,distances = model(images)

        loss = criterion(outputs, labels)


        loss.backward()

        optimizer.step()


        running_loss += loss.item()


        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()


    accuracy = 100 * correct / total


    print(f"\nEpoch [{epoch+1}/{num_epochs}]")

    print(f"Loss: {running_loss/len(train_loader):.4f}")

    print(f"Train Accuracy: {accuracy:.2f}%")

import torch.nn.functional as F

def get_confidence(model, image_tensor):

    model.eval()

    with torch.no_grad():

        output,distances = model(image_tensor)
        min_distance=distances.min().item();

        probabilities = F.softmax(output, dim=1)

        confidence, prediction = torch.max(probabilities, 1)


    return (
        prediction.item(),
        confidence.item(),
        probabilities.cpu().numpy()
    )

#for param in model.features.parameters():
    #param.requires_grad = True

#optimizer = optim.Adam(
    #model.parameters(),
    #lr=0.0001
#)

#fine_tune_epochs = 5

#for epoch in range(fine_tune_epochs):

    #model.train()

    #correct_train = 0
   # total_train = 0


    #for images, labels in train_loader:

        #images = images.to(device)
        #labels = labels.to(device)


        #optimizer.zero_grad()


        #with torch.cuda.amp.autocast():

            #outputs = model(images)

            #loss = criterion(outputs, labels)


        #scaler.scale(loss).backward()

        #scaler.step(optimizer)

       # scaler.update()


       # _, predicted = torch.max(outputs, 1)

       # total_train += labels.size(0)

       # correct_train += (predicted == labels).sum().item()


    #train_accuracy = 100 * correct_train / total_train


    # VALIDATION
   # model.eval()

    #correct_val = 0
   # total_val = 0


   # with torch.no_grad():

       # for images, labels in val_loader:

           # images = images.to(device)
           # labels = labels.to(device)


          #  outputs = model(images)

          #  _, predicted = torch.max(outputs, 1)
          #

          #  total_val += labels.size(0)
          #
          #  correct_val += (predicted == labels).sum().item()


    #val_accuracy = 100 * correct_val / total_val


    #if val_accuracy > best_accuracy:

      #  best_accuracy = val_accuracy

      #  torch.save(model.state_dict(), "best_model.pth")


   # print(f"\nFine-Tune Epoch [{epoch+1}/{fine_tune_epochs}]")

   # print(f"Train Accuracy: {train_accuracy:.2f}%")

    #print(f"Validation Accuracy: {val_accuracy:.2f}%")
   #
   # print(f"Best Accuracy: {best_accuracy:.2f}%")

#model.load_state_dict(torch.load("best_model.pth"))

#model.eval()

#from google.colab import files

#uploaded = files.upload()

from PIL import Image
import matplotlib.pyplot as plt
import torch.nn.functional as F
import os

class_names = ['Cat', 'Dog']

transform_test = transforms.Compose([

    transforms.Resize((224, 224)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

model.eval()

THRESHOLD = 0.7

image_folder = "/content/ood_images/dataset"
image_files = [
    f for f in os.listdir(image_folder)
    if f.lower().endswith(('.jpg', '.jpeg', '.png', '.jfif'))
]

ood_count = 0

for image_name in image_files:

    image_path = os.path.join(image_folder, image_name)

    image = Image.open(image_path).convert('RGB')

    image_tensor = transform_test(image)

    image_tensor = image_tensor.unsqueeze(0)

    image_tensor = image_tensor.to(device)

    with torch.no_grad():

        logits, distances = model(image_tensor)

        probabilities = F.softmax(logits, dim=1)

        confidence, prediction = torch.max(probabilities, 1)

        confidence_score = confidence.item()

    if confidence_score < THRESHOLD:

        print(f"{image_name} --> Unknown (OOD Detected) | Confidence: {confidence_score*100:.2f}%")
        ood_count += 1

    else:

        predicted_class = class_names[prediction.item()]

        print(f"{image_name} --> {predicted_class} | Confidence: {confidence_score*100:.2f}%")

print("-" * 60)
print(f"Detected {ood_count} out of {len(image_files)} images as OOD")
print(f"OOD Detection Rate: {(ood_count/len(image_files))*100:.2f}%")