# -*- coding: utf-8 -*-
"""Final_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12nmPpbUub3paSZgXlct4lWRgJd6yVABp
"""

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader, random_split

from PIL import ImageFile

ImageFile.LOAD_TRUNCATED_IMAGES = True

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

from google.colab import drive
drive.mount('/content/drive')

!unzip "/content/drive/MyDrive/dataset/archive.zip" -d "/content/dataset"

'''!unzip -q "/content/drive/MyDrive/ood/ood.zip" -d "/content/ood_images"

print("OOD dataset extracted!")

import os

print(os.listdir("/content/dataset"))

import os

print(os.listdir("/content/drive/MyDrive/dataset (1)")[:20])
print("Count:", len(os.listdir("/content/drive/MyDrive/dataset (1)")))

train_transform = transforms.Compose([

    transforms.Resize((224, 224)),

    transforms.RandomHorizontalFlip(),

    transforms.RandomRotation(10),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


val_transform = transforms.Compose([

    transforms.Resize((224, 224)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

full_dataset = datasets.ImageFolder(
    root="/content/dataset/PetImages"
)
print(full_dataset.classes)

full_dataset = datasets.ImageFolder(
    root="/content/dataset/PetImages"
)

train_size = int(0.8 * len(full_dataset))
val_size = len(full_dataset) - train_size

train_dataset, val_dataset = random_split(
    full_dataset,
    [train_size, val_size]
)

train_dataset.dataset.transform = train_transform

val_dataset.dataset.transform = val_transform

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True,
    num_workers=2
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2
)

class GaussianClassifier(nn.Module):

    def __init__(self,
                 in_features=1280,
                 hidden_dim=32,
                 num_classes=2):

        super().__init__()

        self.mu1 = nn.Parameter(
            torch.zeros(in_features)
        )

        self.sigma1 = nn.Parameter(
            torch.ones(in_features)
        )

        self.fc1 = nn.Linear(
            in_features,
            hidden_dim
        )

        self.relu = nn.ReLU()

        self.fc2 = nn.Linear(
            hidden_dim,
            num_classes
        )

        self.mu2 = nn.Parameter(
            torch.zeros(num_classes)
        )

        self.sigma2 = nn.Parameter(
            torch.ones(num_classes)
        )

    def forward(self, x, print_z=False):

        sigma1 = torch.abs(self.sigma1) + 1e-6

        z1 = (x - self.mu1) / sigma1

        z = self.fc1(z1)

        z = self.relu(z)

        z = self.fc2(z)

        sigma2 = torch.abs(self.sigma2) + 1e-6

        z2 = (z - self.mu2) / sigma2

        if print_z:

            print("\n===== Z1 Summary =====")
            print("Mean :", z1.mean().item())
            print("Std  :", z1.std().item())

            print("\n===== Z2 =====")
            print(z2.detach().cpu().numpy())

        return z2

model = models.efficientnet_b0(pretrained=True)

num_features = model.classifier[1].in_features

model.classifier[1] = GaussianClassifier(
    in_features=num_features,
    hidden_dim=32,
    num_classes=2
)

model = model.to(device)

for param in model.features.parameters():
    param.requires_grad = False

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.classifier.parameters(),
    lr=1e-4
)

#scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    #optimizer,
    #mode='min',
    #factor=0.5,
    #patience=1
#)

scaler = torch.cuda.amp.GradScaler()

num_epochs = 10

for epoch in range(num_epochs):

    model.train()

    running_loss = 0.0

    correct = 0
    total = 0


    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)


        optimizer.zero_grad()


        outputs = model(images)

        loss = criterion(outputs, labels)


        loss.backward()

        optimizer.step()


        running_loss += loss.item()


        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()


    accuracy = 100 * correct / total


    print(f"\nEpoch [{epoch+1}/{num_epochs}]")

    print(f"Loss: {running_loss/len(train_loader):.4f}")

    print(f"Train Accuracy: {accuracy:.2f}%")

import torch
import torch.nn.functional as F

def get_confidence(model, image_tensor):

    model.eval()

    with torch.no_grad():

        z2 = model(
            image_tensor,
            print_z=True
        )

        print("\nRaw Z2:")
        print(z2.cpu().numpy())

        probabilities = F.softmax(
            z2,
            dim=1
        )

        print("\nProbabilities:")
        print(probabilities.cpu().numpy())

        confidence, prediction = torch.max(
            probabilities,
            1
        )

    return (
        prediction.item(),
        confidence.item(),
        probabilities.cpu().numpy()
    )

from PIL import Image
import torch
import torch.nn.functional as F
import os

class_names = ['cat', 'dog']

THRESHOLD = 0.7

image_folder = "/content/drive/MyDrive/dataset (1)"

image_files = [
    f for f in os.listdir(image_folder)
    if f.lower().endswith(
        ('.jpg', '.jpeg', '.png', '.jfif')
    )
]

ood_count = 0

model.eval()

for image_name in image_files:

    image_path = os.path.join(
        image_folder,
        image_name
    )

    image = Image.open(
        image_path
    ).convert("RGB")

    image_tensor = val_transform(
        image
    ).unsqueeze(0).to(device)

    with torch.no_grad():

        features = model.features(
            image_tensor
        )

        features = model.avgpool(
            features
        )

        features = torch.flatten(
            features,
            1
        )

        z2 = model.classifier[1](
            features,
            print_z=False
        )

        probabilities = F.softmax(
            z2,
            dim=1
        )

        confidence, prediction = torch.max(
            probabilities,
            1
        )

        confidence_score = (
            confidence.item()
        )

    if confidence_score < THRESHOLD:

        print(
            f"{image_name} --> UNKNOWN (OOD) | "
            f"Confidence: {confidence_score*100:.2f}%"
        )

        ood_count += 1

    else:

        predicted_class = class_names[
            prediction.item()
        ]

        print(
            f"{image_name} --> {predicted_class} | "
            f"Confidence: {confidence_score*100:.2f}%"
        )

print("\n" + "-"*60)

print(
    f"Detected {ood_count} out of "
    f"{len(image_files)} images as OOD"
)

print(
    f"OOD Detection Rate: "
    f"{100*ood_count/len(image_files):.2f}%"
)